FoodOrderingSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    #when someone clicks the accounts it should navigate to url in accounts app
    path('',include('accounts.urls')),
    path('marketplace/', include('marketplace.urls')),

    # CART
    path('cart/', MarketplaceViews.cart, name='cart'),
    # SEARCH
    path('search/', MarketplaceViews.search, name='search'),

    # CHECKOUT
    path('checkout/', MarketplaceViews.checkout, name='checkout'),

    # ORDERS
    path('orders/', include('orders.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('place_order/',views.place_order,name='place_order'),
    path('payments/',views.payments,name='payments'),
    path('order_complete/',views.order_complete,name='order_complete')
]

restaurant/urls.py
from django.urls import path, include
from . import views
from accounts import views as AccountViews


urlpatterns = [
    path('', AccountViews.restaurantDashboard, name='restaurant'),
    path('profile/', views.rprofile, name='rprofile'),
    path('menu-builder/', views.menu_builder, name='menu_builder'),
    path('menu-builder/category/<int:pk>/', views.fooditems_by_category, name='fooditems_by_category'),

    # Category CRUD
    path('menu-builder/category/add/', views.add_category, name='add_category'),
    path('menu-builder/category/edit/<int:pk>',views.edit_category,name='edit_category'),
    path('menu-builder/category/delete/<int:pk>',views.delete_category,name='delete_category'),
 

    # # FoodItem CRUD
    
    
    
    path('menu-builder/food/add',views.add_food,name='add_food'),
    path('menu-builder/food/delete/<int:pk>',views.delete_food,name='delete_food'),
    path('menu-builder/food/edit/<int:pk>',views.edit_food,name='edit_food'),
    
    
    
    # path('menu-builder/food/add/', views.add_food, name='add_food'),
    # path('menu-builder/food/edit/<int:pk>/', views.edit_food, name='edit_food'),
    # path('menu-builder/food/delete/<int:pk>/', views.delete_food, name='delete_food'),

    # # Opening Hour CRUD
    path('opening-hours/', views.opening_hours, name='opening_hours'),
    path('opening-hours/add/', views.add_opening_hours, name='add_opening_hours'),
    path('opening-hours/remove/<int:pk>/', views.remove_opening_hours, name='remove_opening_hours'),

    path('order_detail/<int:order_number>/', views.order_detail, name='restaurant_order_detail'),
    path('my_orders/', views.my_orders, name='restaurant_my_orders'),

]

orders/models.py
import json
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from restaurant.models import Restaurant


request_object = ''

class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PayPal', 'PayPal'),
        ('RazorPay', 'RazorPay'), # Only for Indian Students.
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    restaurants = models.ManyToManyField(Restaurant, blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text = "Data format: {'tax_type':{'tax_percentage':'tax_amount'}}", null=True)
    total_data = models.JSONField(blank=True, null=True)
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Concatenate first name and last name
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    def order_placed_to(self):
        return ", ".join([str(i) for i in self.restaurants.all()])

    def get_total_by_restaurant(self):
        restaurant = Restaurant.objects.get(user=request_object.user)
        subtotal = 0
        tax = 0
        tax_dict = {}
        if self.total_data:
            total_data = json.loads(self.total_data)
            data = total_data.get(str(restaurant.id))
            
            
            for key, val in data.items():
                subtotal += float(key)
                val = val.replace("'", '"')
                val = json.loads(val)
                tax_dict.update(val)

                # calculate tax
                # {'CGST': {'9.00': '6.03'}, 'SGST': {'7.00': '4.69'}}
                for i in val:
                    for j in val[i]:
                        tax += float(val[i][j])
        grand_total = float(subtotal) + float(tax)
        context = {
            'subtotal': subtotal,
            'tax_dict': tax_dict, 
            'grand_total': grand_total,
        }

        return context

    def __str__(self):
        return self.order_number


class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fooditem.food_title

restaurant/forms.py
from django import forms
from .models import Restaurant ,OpeningHour
from accounts.validators import allow_only_images_validator


class RestaurantForm(forms.ModelForm):
    restaurant_license=forms.FileField(widget=forms.FileInput(attrs={'class':'btn btn-info'}),validators=[allow_only_images_validator])
    
    # restaurant_license = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}))#, validators=[allow_only_images_validator])
    class Meta:
        model = Restaurant
        fields = ['restaurant_name', 'restaurant_license']


class OpeningHourForm(forms.ModelForm):
    class Meta:
        model = OpeningHour
        fields = ['day', 'from_hour', 'to_hour', 'is_closed']

restaurant/views.py
# from unicodedata import category
from urllib import response
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.db import IntegrityError

from menu.forms import CategoryForm , FoodItemForm
from orders.models import Order, OrderedFood
# import restaurant
from .forms import RestaurantForm , OpeningHourForm
from accounts.forms import UserProfileForm

from accounts.models import UserProfile
from .models import  Restaurant ,OpeningHour
from django.contrib import messages

from django.contrib.auth.decorators import login_required, user_passes_test
from accounts.views import check_role_restaurant
from menu.models import Category, FoodItem
from django.template.defaultfilters import slugify


def get_restaurant(request):
    restaurant = Restaurant.objects.get(user=request.user)
    return restaurant


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def rprofile(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    restaurant = get_object_or_404(Restaurant, user=request.user)

    if request.method == 'POST':
        profile_form = UserProfileForm( request.POST, request.FILES,instance=profile)
        restaurant_form = RestaurantForm(request.POST, request.FILES,instance=restaurant)
        if profile_form.is_valid() and restaurant_form.is_valid():
            profile_form.save()
            restaurant_form.save()
            messages.success(request, 'Settings updated.')
            return redirect('rprofile')
        else:
            print(profile_form.errors)
            print(restaurant_form.errors)
    else:
        profile_form = UserProfileForm(instance = profile)
        restaurant_form = RestaurantForm(instance=restaurant)

    context = {
        'profile_form': profile_form,
        'restaurant_form': restaurant_form,
        'profile': profile,
        'restaurant': restaurant,
    }
    return render(request, 'restaurant/rprofile.html',context)


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def menu_builder(request):
    restaurant = get_restaurant(request)
    categories = Category.objects.filter(restaurant=restaurant).order_by('created_at')
    context = {
        'categories': categories,
    }
    return render(request, 'restaurant/menu_builder.html',context)


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def fooditems_by_category(request, pk=None):
    restaurant = get_restaurant(request)
    category = get_object_or_404(Category, pk=pk)
    fooditems = FoodItem.objects.filter(restaurant=restaurant, category=category)
    context = {
        'fooditems': fooditems,
        'category': category,
    }
    return render(request, 'restaurant/fooditems_by_category.html', context)


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        try:
            if form.is_valid():
                category_name = form.cleaned_data['category_name']
                category = form.save(commit=False)
                category.restaurant = get_restaurant(request)
                category.save()
                
                category.slug = slugify(category_name)+'-'+str(category.id)# chicken-15
                category.save()
                messages.success(request, 'Category added successfully!')
                return redirect('menu_builder')
        except:
            messages.error(request, 'category exists')
            print(form.errors)

    else:
        form =CategoryForm()
    context = {
        'form': form,
    }
    return render(request, 'restaurant/add_category.html',context)


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def edit_category(request, pk=None):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category_name = form.cleaned_data['category_name']
            category = form.save(commit=False)
            category.restaurant = get_restaurant(request)
            category.slug = slugify(category_name)
            form.save()
            messages.success(request, 'Category updated successfully!')
            return redirect('menu_builder')
        else:
            print(form.errors)

    else:
        form = CategoryForm(instance=category)
    context = {
        'form': form,
        'category': category,
    }
    return render(request, 'restaurant/edit_category.html', context)


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def delete_category(request, pk=None):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    messages.success(request, 'Category has been deleted successfully!')
    return redirect('menu_builder')


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def add_food(request):
    form=FoodItemForm()
    if request.method == 'POST':
        form = FoodItemForm(request.POST, request.FILES)
        if form.is_valid():
            foodtitle = form.cleaned_data['food_title']
            food = form.save(commit=False)
            food.restaurant = get_restaurant(request)
            food.slug = slugify(foodtitle)
            form.save()
            messages.success(request, 'Food Item added successfully!')
            return redirect('fooditems_by_category', food.category.id)
        else:
            print(form.errors)
    else:
        form = FoodItemForm()
        # modify this form
        form.fields['category'].queryset = Category.objects.filter(restaurant=get_restaurant(request))
    context = {
        'form': form,
    }
    return render(request, 'restaurant/add_food.html',context)



@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def edit_food(request, pk=None):
    food = get_object_or_404(FoodItem, pk=pk)
    if request.method == 'POST':
        form = FoodItemForm(request.POST, request.FILES, instance=food)
        if form.is_valid():
            foodtitle = form.cleaned_data['food_title']
            food = form.save(commit=False)
            food.restaurant = get_restaurant(request)
            food.slug = slugify(foodtitle)
            form.save()
            messages.success(request, 'Food Item updated successfully!')
            return redirect('fooditems_by_category', food.category.id)
        else:
            print(form.errors)

    else:
        form = FoodItemForm(instance=food)
        form.fields['category'].queryset = Category.objects.filter(restaurant=get_restaurant(request))
    context = {
        'form': form,
        'food': food,
    }
    return render(request, 'restaurant/edit_food.html', context)


@login_required(login_url='login')
@user_passes_test(check_role_restaurant)
def delete_food(request, pk=None):
    food = get_object_or_404(FoodItem, pk=pk)
    food.delete()
    messages.success(request, 'Food Item has been deleted successfully!')
    return redirect('fooditems_by_category', food.category.id)


def opening_hours(request):
    opening_hours = OpeningHour.objects.filter(restaurant=get_restaurant(request))
    form = OpeningHourForm()
    context = {
        'form': form,
        'opening_hours': opening_hours,
    }
    return render(request, 'restaurant/opening_hours.html', context)


def add_opening_hours(request):
    # return HttpResponse("add apening hour")
#     # handle the data and save them inside the database
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'POST':
            day = request.POST.get('day')
            from_hour = request.POST.get('from_hour')
            to_hour = request.POST.get('to_hour')
            is_closed = request.POST.get('is_closed')
            
            try:
                hour = OpeningHour.objects.create(restaurant=get_restaurant(request), day=day, from_hour=from_hour, to_hour=to_hour, is_closed=is_closed)
                if hour:
                    day = OpeningHour.objects.get(id=hour.id)
                    if day.is_closed:
                        response = {'status': 'success', 'id': hour.id, 'day': day.get_day_display(), 'is_closed': 'Closed'}
                    else:
                        response = {'status': 'success', 'id': hour.id, 'day': day.get_day_display(), 'from_hour': hour.from_hour, 'to_hour': hour.to_hour}
                return JsonResponse(response)
            except IntegrityError as e:
                response = {'status': 'failed', 'message': from_hour+'-'+to_hour+' already exists for this day!'}
                return JsonResponse(response)
        else:
            HttpResponse('Invalid request')


def remove_opening_hours(request, pk=None):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            hour = get_object_or_404(OpeningHour, pk=pk)
            hour.delete()
            return JsonResponse({'status': 'success', 'id': pk})


def order_detail(request, order_number):
    try:
        order = Order.objects.get(order_number=order_number, is_ordered=True)
        ordered_food = OrderedFood.objects.filter(order=order, fooditem__restaurant=get_restaurant(request))

        context = {
            'order': order,
            'ordered_food': ordered_food,
            'subtotal': order.get_total_by_restaurant()['subtotal'],
            'tax_data': order.get_total_by_restaurant()['tax_dict'],
            'grand_total': order.get_total_by_restaurant()['grand_total'],
        }
    except:
        return redirect('restaurant')
    return render(request, 'restaurant/order_detail.html', context)


def my_orders(request):
    restaurant = Restaurant.objects.get(user=request.user)

templates/restaurant/add_category.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Section Start -->
<div class="main-section">
    {% include 'includes/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- Load the sidebar here -->
                    {% include 'includes/r_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Build Your Food Menu</h5>
							<hr>
                            <h6>Add New Category</h6>
                           <form action="{% url 'add_category' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-fields-set">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="field-holder">
                                            <label >Category Name *</label>
                                            {{form.category_name}}
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="field-holder">
                                            <label >Description</label>
                                            {{form.description}}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {% for field in form %}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <li style="color: red;">{{ error }}</li>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}

                            <button type="submit" class="btn btn-info"><i class="fa fa-check" aria-hidden="true"></i> Create</button>
                        </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% include 'includes/alerts.html' %}

{% endblock %}

templates/restaurant/edit_category.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Section Start -->
<div class="main-section">
    {% include 'includes/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- Load the sidebar here -->
                    {% include 'includes/r_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Build Your Food Menu</h5>
							<hr>
                            <button class="btn btn-secondary" onclick="history.back()"><i class="fa fa-angle-left" aria-hidden="true"></i> Back</button>
                            <br><br>
                            <h6>Modify Category</h6>
                            <form action="{% url 'edit_category' category.id %}" method="POST">
                                {% csrf_token %}
                                <div class="form-fields-set">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12">
                                            <div class="field-holder">
                                                <label >Category Name *</label>
                                                {{form.category_name}}
                                            </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12 col-sm-12">
                                            <div class="field-holder">
                                                <label >Description</label>
                                                {{form.description}}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {% for field in form %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <li style="color: red;">{{ error }}</li>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}

                                <button type="submit" class="btn btn-info"><i class="fa fa-check" aria-hidden="true"></i> Update</button>
                                <a href="{% url 'delete_category' category.id %}" onclick="return confirm('Are you sure you want to delete this category?')" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
                            </form>

                            <!-- render form -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% include 'includes/alerts.html' %}

{% endblock %}

templates/restaurant/rprofile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% include 'includes/alerts.html' %}

<!-- Main Section Start -->
<div class="main-section">
    {% include 'includes/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- Load the sidebar here -->
                    {% include 'includes/r_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Manage Your Restaurant</h5>
									<!-- My Restaurants Form Start -->
									<form action="{% url 'rprofile' %}" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
										<div class="form-fields-set">
											<ul>
												<li>
													<div class="row">
														
														<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
															<div class="restaurant-info">
																<div class="img-holder">
																	<ul class="foodbakery-gallery-holder">
																		<li class="gal-img">
																			<div class="drag-list">
																				<div class="item-thumb">
																					{% if profile.profile_picture %}
																					<img class="thumbnail" src="{{profile.profile_picture.url}}" alt="Profile Picture">
																					{% else %}
																					<img class="thumbnail" src="{% static 'images/default-profile.png' %}" alt="Profile Picture">
																					{% endif %}
																				</div>
																			</div>
																		</li>
																	</ul>
																</div>
																<div class="text-holder">
																	<label>Update Profile Picture</label>
																	<div class="upload-gallery">
																		{{profile_form.profile_picture}}
																	</div>
																</div>
																<label class="text-danger">{{ profile_form.profile_picture.errors }}</label>
															</div>
														</div>
														<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
															<div class="restaurant-info">
																<div class="img-holder">
																	<ul class="foodbakery-gallery-holder">
																		<li class="gal-img">
																			<div class="drag-list">
																				<div class="item-thumb">
																					{% if profile.cover_photo %}
																					<img class="thumbnail" src="{{profile.cover_photo.url}}" alt="Cover Photo">
																					{% else %}
																					<img class="thumbnail" src="{% static 'images/default-cover.png' %}" alt="Cover Photo">
																					{% endif %}
																				</div>
																			</div>
																		</li>
																	</ul>
																</div>
																<div class="text-holder">
																	<label>Update Cover Photo</label>
																	<div class="upload-gallery">
																		{{profile_form.cover_photo}}
																	</div>
																	
																</div>
																<label class="text-danger">{{ profile_form.cover_photo.errors }}</label>
															</div>
														</div>
														<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
															<div class="restaurant-info">
																<div class="img-holder">
																	<ul class="foodbakery-gallery-holder">
																		<li class="gal-img">
																			<div class="drag-list">
																				<div class="item-thumb">
																					<img class="thumbnail" src="{{restaurant.restaurant_license.url}}" alt="Vendor License">
																				</div>
																			</div>
																		</li>
																	</ul>
																</div>
																<div class="text-holder">
																	<label>Update License</label>
																	<div class="upload-gallery">
																		{{restaurant_form.restaurant_license}}
																	</div>
																	
																</div>
																<label class="text-danger">{{ restaurant_form.restaurant_license.errors }}</label>
															</div>
														</div>
														<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>Restaurant name *</label>
																{{restaurant_form.restaurant_name}}
															</div>
														</div>
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>Address *</label>
																<input type='input' name="address" required="" id="id_address" placeholder="Start Typing..." style="">
																{% comment %} {{profile_form.address}} {% endcomment %}
																<small class="text-muted float-right">powered by Google</small>
															</div>
														</div>
                                                        

                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>Country *</label>
																{{profile_form.country}}
															</div>
														</div>

                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>State *</label>
																{{profile_form.state}}
															</div>
														</div>

                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>City *</label>
																{{profile_form.city}}
															</div>
														</div>

                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>Pin Code *</label>
																{{profile_form.pin_code}}
															</div>
														</div>

                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>Latitude *</label>
																{{profile_form.latitude}}
															</div>
														</div>

                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
															<div class="field-holder">
																<label>Longitude *</label>
																{{profile_form.longitude}}
															</div>
														</div>


														
													</div>
												</li>
											</ul>
											<div>
												<div class="field-holder">
													<div class="payment-holder input-button-loader">
														<input type="submit" value="Update Restaurant">
													</div>
												</div>
											</div>
										</div>
									</form>
									<!-- My Restaurants Form End -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock %}